In [2]:
list = [1,2,3,
        4,5,6,
        7,8,9,]

list_2d = [[1,2,3],
           [4,5,6],
           [7,8,9],]

In [3]:
print(list)
print(list_2d)

print(list[1])
print(list_2d[0][1])

print(len(list))
print(len(list_2d))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2
2
9
3


In [17]:
def matmul(A, B):
    m = len(A)         # A의 행 개수
    n = len(A[0])      # A의 열 개수 == B의 행 개수
    p = len(B[0])      # B의 열 개수

    # 결과 행렬 C 초기화 (m x p)
    C = [[0 for _ in range(p)] for _ in range(m)]

    # 행렬곱 계산
    for i in range(m):          # A의 행
        for j in range(p):      # B의 열
            for k in range(n):  # A의 열 == B의 행
                C[i][j] += A[i][k] * B[k][j]

    return C

In [8]:
matrix_1 = [[1,2,3],
            [4,5,6],
            [7,8,9],]

matrix_2 = [[3,0,0],
            [0,1,0],
            [0,0,1],]

In [21]:
matrix_3 = matmul(matrix_1, matrix_2)
print(matrix_3)

[[3, 2, 3], [12, 5, 6], [21, 8, 9]]


In [19]:
vector_1 = [[1,2,3]]
matrix_4 = matmul(vector_1, matrix_3)

print(matrix_4)

[[90, 36, 42]]


In [22]:
import numpy as np

# 기본 행렬 정의
matrix_1 = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_2 = np.array([[3, 0, 0],
                     [0, 1, 0],
                     [0, 0, 1]])

# 행렬곱 (dot or @)
matrix_3 = matrix_1 @ matrix_2   # 또는 np.dot(matrix_1, matrix_2)

print("matrix_3 (NumPy):")
print(matrix_3)

# 벡터 정의 및 곱
vector_1 = np.array([[1, 2, 3]])
matrix_4 = vector_1 @ matrix_3

print("matrix_4 (NumPy):")
print(matrix_4)

matrix_3 (NumPy):
[[ 3  2  3]
 [12  5  6]
 [21  8  9]]
matrix_4 (NumPy):
[[90 36 42]]


In [24]:
import torch

# 텐서 정의
matrix_1 = torch.tensor([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]], dtype=torch.float)

matrix_2 = torch.tensor([[3, 0, 0],
                         [0, 1, 0],
                         [0, 0, 1]], dtype=torch.float)

# 행렬곱 (matmul 또는 @ 연산자)
matrix_3 = matrix_1 @ matrix_2

print("matrix_3 (Torch):")
print(matrix_3)

# 벡터 정의 및 곱
vector_1 = torch.tensor([[1, 2, 3]], dtype=torch.float)
matrix_4 = vector_1 @ matrix_3

print("matrix_4 (Torch):")
print(matrix_4)


matrix_3 (Torch):
tensor([[ 3.,  2.,  3.],
        [12.,  5.,  6.],
        [21.,  8.,  9.]])
matrix_4 (Torch):
tensor([[90., 36., 42.]])
